### ISSUE TITLE
How to take a screenshot ?

### ISSUE THREAD

**Issue by GuacheSuede** [amitbet/vnc2video#2]

**Comment by amitbet** [comment]
You can use the client in the examples directory and modify the mjpeg encoder to save to file after encoding a jpeg instead of sending it into an avi...

**The encoder code can be found here:**
https://github.com/amitbet/vnc2video/blob/master/encoders/mjpeg-enc.go

all you need to do to get jpeg frames on disk is write the frame bytes to individual files:
**comment out:**
err = enc.avWriter.AddFrame(buf.Bytes())

**use this line to write to a filename of your choosing:**
err := ioutil.WriteFile("/path/filename", buf.Bytes(), 0644)

**Comment by GuacheSuede** [comment]
Thanks. How does one use the RGBSubimage function with the client ?

**Comment by GuacheSuede** [comment]
> You can use the client in the examples directory and modify the mjpeg encoder to save to file after encoding a jpeg instead of sending it into an avi...
> 
> **The encoder code can be found here:**
> https://github.com/amitbet/vnc2video/blob/master/encoders/mjpeg-enc.go
> 
> all you need to do to get jpeg frames on disk is write the frame bytes to individual files:
> **comment out:**
> err = enc.avWriter.AddFrame(buf.Bytes())
> 
> **use this line to write to a filename of your choosing:**
> err := ioutil.WriteFile("/path/filename", buf.Bytes(), 0644)

In main.go example, couldnt i just use "FramebufferUpdateMsgType" to get the image buffer and encode it ?

**Comment by GuacheSuede** [comment]
Get image from this line ?
https://github.com/amitbet/vnc2video/blob/master/example/client/main.go#L61

**Comment by amitbet** [comment]
Sure, just use screenImage.Image to get the image and encode it to any image format. 

Just make sure you have an image first by checking you have recieved the first frame  buffer update response. (so you don't have a blank screen)
