### ISSUE TITLE
compile error to windows 386

### ISSUE THREAD

**Issue by linpinger** [amitbet/vnc2video#8]
when compile vnc2video\example\file-reader\main.go to `windows`  `amd64`    everything is ok, and works fine
but when

`set GOOS=windows`
`set GOARCH=386`
`go build main.go`

error message:
` # github.com/amitbet/vnc2video`
` src\github.com\amitbet\vnc2video\encoding_zrle.go:46:40: constant 4278190080 overflows int`

so i change:
`significant := int(pf.RedMax<<pf.RedShift | pf.GreenMax<<pf.GreenShift | pf.BlueMax<<pf.BlueShift)`
to:
`significant := int64(pf.RedMax<<pf.RedShift | pf.GreenMax<<pf.GreenShift | pf.BlueMax<<pf.BlueShift)`

don't known is this ok ?

plus:
  how can i speed up trans fbs 2 mp4 ?   3 times speed is too slow

**Comment by amitbet** [comment]
your change should be ok, since 'int' depends on the architecture and when compiling to 64 bit it would be int64, just that in 386 you get int = int32, so changing it makes sense.

about the speed of encoding, this is the main reason that this vnc2video project remained an experiment.. encoding on the fly with reasonable CPU power usually can't catch up to the stream.
it is a rather complete implementation of vnc viewer in golang, which i enjoyed writing, but the video part, though working, is not really production grade... we ended up using vnc2flv to store the video in a semi-compressed format and encoding it later with a cloud encoder.

if you are interested in further developing this, i would look at connecting it directly to some simple video format encoder (maybe in pure go) that can quickly offload the images to disk, i would also try to get a better image capturer that would provide video or at least a better input frame rate than the current snapshot code i have there.

**Comment by amitbet** [comment]
another option is to use my vncproxy project to offload the actual rfb stream to disk and replay it later from that format.

**Comment by linpinger** [comment]
thanks for your reply
i tested and try some options.
the best method is record vnc 2 rfb, then can trans rfb 2 flv/mp4, it worked good
Thanks Again
